version: '3'

services:
  notebook:
    build: .  # ビルド対象のDockerfileが同じフォルダ内にあるため
    environment:
      - GRANT_SUDO=yes
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    working_dir: /home/jovyan/work
    user: root
    volumes:
      - type: bind
        source: ../src
        target: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''